[Settings]
widthWindow = 1000
heightWindow = 1000
font = "Jersey10-Regular.ttf"

[Resources]
texture = [
    { name = "Robot", path = "robak.png" },
    { name = "Spaceship", path = "statek.png" }
]

[Entity]
enemy = [
    { name = "v1", texture = "Robot",health = 3 ,damage = 1, bulletSpeed = 400 },
    { name = "v2", texture = "Robot",health = 4 ,damage = 3, bulletSpeed = 400 }
]

player = [
    { name = "level1", texture = "Spaceship",health = 3 ,damage = 3, bulletSpeed = 600 }
]

[Layout]
level = [
    { name = "level_V1", player = "level1", layout = [
        ["v2","v2","v2","v2"],
        ["v1","v1","v1","v1"]
    ],lines = [10,60,110,160,210,260,310,360] }
]

game = [
    { name = "easy", levels = [
        "level_V1",
        "level_V1",
        "level_V1"
    ]},
    { name = "easy2yyyyyyyyyyyyyyyyyyyyyyy", levels = [
        "level_V1",
        "level_V1",
        "level_V1"
    ]},
    { name = "easy3", levels = [
        "level_V1",
        "level_V1",
        "level_V1"
    ]}
]