[Settings]
widthWindow = 1000
heightWindow = 1000
font = "Jersey10-Regular.ttf"

[Resources]
texture = [
    { name = "Robot", path = "robak.png" },
    { name = "Robot2", path = "robak2.png" },
    { name = "Alien1_1", path = "kosmita1_1.png" },
    { name = "Alien1_2", path = "kosmita1_2.png" },
    { name = "Alien2_1", path = "kosmita2_1.png" },
    { name = "Alien2_2", path = "kosmita2_2.png" },
    { name = "Spaceship", path = "statek.png" }
]

[Entity]
enemy = [
    { name = "v1", texture = "Robot;Robot2",health = 3 ,damage = 3, bulletSpeed = 400, bulletDelay = 3},
    { name = "v2", texture = "Alien1_1;Alien1_2",health = 8 ,damage = 5, bulletSpeed = 300, bulletDelay = 3},
    { name = "v3", texture = "Alien2_1;Alien2_2",health = 4 ,damage = 5, bulletSpeed = 600, bulletDelay = 1}
]

player = [
    { name = "level1", texture = "Spaceship",health = 10 ,damage = 3, bulletSpeed = 600, bulletDelay = 0.2},
    { name = "level2", texture = "Spaceship",health = 5 ,damage = 3, bulletSpeed = 500, bulletDelay = 0.1}
]

[Layout]
wall = [
    { name = "wall1", count = 4 ,x = 15, y = 10, height = 250, cut = 5},
    { name = "wall2", count = 2 ,x = 20, y = 10, height = 250, cut = 3},
    { name = "pyramid", count = 1 ,x = 180, y = 60, height = 500, cut = 2}
]

level = [
    { name = "level_V1", end = "next_level", player = "level1", playerSpeed = 400, enemySpeed = 200, wall = "wall1", layout = [
        ["v2","v2","v2","v2"],
        ["v1","v1","v1","v1"]
    ],lines = [10,60,110,160,210,260,310,360] },

    { name = "level_V2", end = "you won", player = "level1", playerSpeed = 400, enemySpeed = 300, wall = "wall2", layout = [
        ["v3","v2","v2","v3"]
    ],lines = [10,60,110,160,210,260,310,360] },

    { name = "level_pyramid", end = "-->>", player = "level2", playerSpeed = 600, enemySpeed = 500, wall = "pyramid", layout = [
        ["v3","v3","v3","v3"]
    ],lines = [10,60,110,160,210,260,310,360] },

    { name = "level_full", end = "-->>", player = "level1", playerSpeed = 400, enemySpeed = 200, wall = "wall1", layout = [
        ["v3","v3","v3","v3","v3","v3","v3","v3","v3"],
        ["v2","v2","v2","v2","v2","v2","v2","v2","v2"],
        ["v1","v2","v3","v1","v1","v1","v3","v2","v1"],
        ["v1","v3","v3","v1","v2","v1","v3","v3","v1"],
        ["v1","v1","v1","v1","v1","v1","v1","v1","v1"],
    ],lines = [10,60,110,160,210,260,310,360] }
]

game = [
    { name = "mini", levels = [
        "level_V1",
        "level_V2",
    ]},
    { name = "pyramid", levels = [
        "level_pyramid",
    ]},
    { name = "full", levels = [
        "level_full",
    ]}
]