[Resources]
texture = [
    { name = "Robot", path = "robak.png" },
    { name = "Spaceship", path = "statek.png" }
]

[Entity]
enemy = [
    { name = "v1", texture = "Robot",health = 3 ,damage = 1 },
    { name = "v2", texture = "Robot",health = 4 ,damage = 3 }
]

player = [
    { name = "level1", texture = "Spaceship",health = 3 ,damage = 3 }
]

[Layout]
level = [
    { name = "level_V1", layout = [
        ["v2","v2","v2","v2"],
        ["v1","v1","v1","v1"]
    ]}
]

game = [
    { name = "easy", levels = [
        "level_V1",
        "level_V1",
        "level_V1"
    ]}
]